def main():
	
	adjective = raw_input("Enter an Adjective ")
	adjective2 = raw_input("Enter an Adjective ")
	bird = raw_input("Enter a type of bird ")
	room = raw_input("Enter a room in a House ")
	verb = raw_input("Enter a Verb with past tense ")
	verb2 = raw_input("Enter a Verb ")
	name = raw_input("Enter a Relatives Name ")
	noun = raw_input("Enter a Noun ")
	liquid = raw_input("Enter a type of Liquid ")
	verb3 = raw_input("Enter a Verb ending in ing ")
	body = raw_input("Enter a Body Part Plural ")
	noun2 = raw_input("Enter a Plural Noun ")
	verb4 = raw_input("Enter a Verb ending in ing ")
	noun3 = raw_input("Enter a Noun ")
	print("It was a " + adjective + " ,cold November day. I woke up to the " + adjective2 + " smell of " + bird + " roasting in the " + room + " downstairs, I " + verb + " down the stairs to see if i could help " + verb2 + " the dinner. My mom said, 'See if " + name + " needs a fresh " + noun + ".' So I carried a tray of glasses full of " + liquid + " into the " + verb3 + " room. When I got there, I couldn't believe my " + body + "! There were " + noun2 + " " + verb4 + " on the " + noun3 + "! ")
	main()
main()